FROM golang:1.24.4-alpine3.21 AS builder

WORKDIR /app

COPY internal ./internal/
COPY pkg ./pkg/
COPY cmd ./cmd/
COPY go.mod go.sum ./

RUN go mod download && \
    go build -o bin/main ./cmd/main.go


FROM alpine:3.21

WORKDIR /app


COPY --from=builder /app/bin/main .
COPY config/ /config/

CMD ["./main"]