version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skill_space
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  skillspace:
    container_name: skillspace
    build:
      context: .
      dockerfile: Dockerfile.yaml
    environment:
      # GIN_MODE: release
      DB_HOST: postgres
      HOST: 0.0.0.0
    depends_on:
    - postgres
    ports:
    - "8080:8080"



volumes:
  db_data:
    driver: local
